---

- name: GUI packages
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - asciinema
    - chromium-browser
    - gparted
    - inkscape
    - mypaint
    - qtpass
    - simplescreenrecorder
    - vlc
    - gimp
  become: true

- import_tasks: sublime-text-3.yml
- import_tasks: tilix.yml
- import_tasks: dropbox.yml
- import_tasks: vscode.yml
- import_tasks: jetbrains.yml

- name: Show date in gnome panel
  shell: "gsettings set org.gnome.desktop.interface clock-show-date true"
