---

- name: "VSCode: Get GPG Key"
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
  become: true

- name: "VSCode: Add APT Repository"
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'
    filename: vscode
  become: true

- name: "VSCode: Install"
  apt:
    name: code
    state: latest
  become: true