---

- name: Install Java
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - default-jdk

- name: Create zsh-env directory
  file: path="/home/{{ username }}/.config/zsh-env/" state=directory

- name: Link java.zsh
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/{{ username }}/.config/zsh-env/{{ item }}"
    state: link
  with_items:
    - java.zsh
